export const MOCK_DOCTORS = [
  {
    _id: 'doc1',
    name: 'Dr. Rahul Sharma',
    specialization: 'Cardiologist',
    qualification: 'MBBS, MD',
    experience: '12 Years Experience',
    clinicName: 'ABC Healthcare Clinic',
    city: 'Rourkela',
    state: 'Odisha',
    locationText: 'Rourkela, Odisha',
    consultationFee: 500,
    rating: 4.8,
    reviewCount: 128,
    image: '/images/doctor_rahul_sharma.png',
    languages: ['English', 'Hindi', 'Odia'],
    bio: 'Dr. Rahul Sharma is a dedicated cardiologist with over 12 years of experience in diagnosing and treating heart-related conditions. He specializes in preventive cardiology and heart health management.',
    availabilityStatus: 'Available Today',
    availableWindows: [
      { id: 'w1', date: '2026-08-20', label: 'Today', dateText: '20 August 2026', timeRange: '10:00 AM - 1:00 PM', status: 'open' },
      { id: 'w2', date: '2026-08-20', label: 'Today', dateText: '20 August 2026', timeRange: '6:00 PM - 8:00 PM', status: 'open' },
      { id: 'w3', date: '2026-08-21', label: 'Tomorrow', dateText: '21 August 2026', timeRange: '10:00 AM - 1:00 PM', status: 'open' },
    ],
  },
  {
    _id: 'doc2',
    name: 'Dr. Priya Verma',
    specialization: 'Dermatologist',
    qualification: 'MBBS, DDVL',
    experience: '8 Years Experience',
    clinicName: 'Skin Care Clinic',
    city: 'Rourkela',
    state: 'Odisha',
    locationText: 'Rourkela, Odisha',
    consultationFee: 400,
    rating: 4.9,
    reviewCount: 94,
    image: '/images/doctor_priya_verma.png',
    languages: ['English', 'Hindi', 'Odia'],
    bio: 'Dr. Priya Verma is a skilled dermatologist providing comprehensive skincare, trichology, and cosmetic dermatology solutions.',
    availabilityStatus: 'Available Today',
    availableWindows: [
      { id: 'w4', date: '2026-08-20', label: 'Today', dateText: '20 August 2026', timeRange: '6:00 PM - 9:00 PM', status: 'open' },
      { id: 'w5', date: '2026-08-21', label: 'Tomorrow', dateText: '21 August 2026', timeRange: '4:00 PM - 7:00 PM', status: 'open' },
    ],
  },
  {
    _id: 'doc3',
    name: 'Dr. Sandeep Jha',
    specialization: 'Orthopedic',
    qualification: 'MBBS, MS',
    experience: '10 Years Experience',
    clinicName: 'Ortho Care Clinic',
    city: 'Rourkela',
    state: 'Odisha',
    locationText: 'Rourkela, Odisha',
    consultationFee: 600,
    rating: 4.7,
    reviewCount: 86,
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
    languages: ['English', 'Hindi', 'Odia'],
    bio: 'Dr. Sandeep Jha is an expert orthopedic surgeon specializing in joint replacement, sports injury treatment, and fracture care.',
    availabilityStatus: 'Available Tomorrow',
    availableWindows: [
      { id: 'w6', date: '2026-08-21', label: 'Tomorrow', dateText: '21 August 2026', timeRange: '10:00 AM - 1:00 PM', status: 'open' },
    ],
  },
  {
    _id: 'doc4',
    name: 'Dr. Anjali Mehta',
    specialization: 'Pediatrician',
    qualification: 'MBBS, DCH',
    experience: '9 Years Experience',
    clinicName: 'Little Hearts Care',
    city: 'Delhi',
    state: 'Delhi',
    locationText: 'Delhi, India',
    consultationFee: 500,
    rating: 4.9,
    reviewCount: 112,
    image: 'https://images.unsplash.com/photo-1594824813571-2b533411efa0?auto=format&fit=crop&w=400&q=80',
    languages: ['English', 'Hindi'],
    bio: 'Dr. Anjali Mehta is a compassionate child specialist dedicated to infant nutrition, vaccination, and adolescent healthcare.',
    availabilityStatus: 'Available Today',
    availableWindows: [
      { id: 'w7', date: '2026-08-20', label: 'Today', dateText: '20 August 2026', timeRange: '11:00 AM - 2:00 PM', status: 'open' },
    ],
  },
];

export const MOCK_CLINICS = [
  {
    _id: 'cl1',
    name: 'ABC Healthcare Clinic',
    uniqueClinicId: 'MED-CLN-8F42K9',
    authorizedEmail: 'contact@abchealthcare.com',
    city: 'Rourkela',
    state: 'Odisha',
    fullAddress: 'Rourkela, Odisha',
    approvalStatus: 'approved',
    isActive: true,
  },
  {
    _id: 'cl2',
    name: 'Skin Care Clinic',
    uniqueClinicId: 'MED-CLN-3D91P4',
    authorizedEmail: 'contact@skincareclinic.com',
    city: 'Rourkela',
    state: 'Odisha',
    fullAddress: 'Rourkela, Odisha',
    approvalStatus: 'approved',
    isActive: true,
  },
  {
    _id: 'cl3',
    name: 'Ortho Care Clinic',
    uniqueClinicId: 'MED-CLN-7K20M8',
    authorizedEmail: 'contact@orthocare.com',
    city: 'Rourkela',
    state: 'Odisha',
    fullAddress: 'Rourkela, Odisha',
    approvalStatus: 'approved',
    isActive: true,
  },
];

export const MOCK_PATIENT = {
  _id: 'pat1',
  name: 'Ashish Raj',
  email: 'ashishraj@gmail.com',
  phone: '+91 98765 43210',
  dob: '12 May 2002',
  gender: 'Male',
  bloodGroup: 'O+',
  address: 'Rourkela, Odisha, India',
  role: 'patient',
  familyMembers: [
    { _id: 'fm1', name: 'Satya Raj', relation: 'Father', age: 54, gender: 'male', phone: '+91 98765 12345' },
    { _id: 'fm2', name: 'Pooja Raj', relation: 'Sister', age: 22, gender: 'female', phone: '+91 98765 67890' },
  ],
};

export const MOCK_APPOINTMENTS = [
  {
    _id: 'apt1',
    doctor: MOCK_DOCTORS[0],
    clinic: MOCK_CLINICS[0],
    date: '20 August 2026',
    timeWindow: '10:00 AM - 1:00 PM',
    status: 'CONFIRMED',
    patientType: 'self',
    patientDetails: { name: 'Ashish Raj (Myself)', age: 24 },
    bookedAt: '2026-08-14T10:00:00Z',
    consultationFee: 500,
  },
  {
    _id: 'apt2',
    doctor: MOCK_DOCTORS[1],
    clinic: MOCK_CLINICS[1],
    date: '25 August 2026',
    timeWindow: '6:00 PM - 9:00 PM',
    status: 'PENDING',
    patientType: 'self',
    patientDetails: { name: 'Ashish Raj (Myself)', age: 24 },
    bookedAt: '2026-08-14T11:30:00Z',
    consultationFee: 400,
  },
  {
    _id: 'apt3',
    doctor: MOCK_DOCTORS[2],
    clinic: MOCK_CLINICS[2],
    date: '10 August 2025',
    timeWindow: '10:00 AM - 1:00 PM',
    status: 'COMPLETED',
    patientType: 'self',
    patientDetails: { name: 'Ashish Raj (Myself)', age: 23 },
    bookedAt: '2025-08-09T09:00:00Z',
    consultationFee: 600,
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    _id: 'n1',
    type: 'appointment_confirmed',
    title: 'Appointment Confirmed',
    message: 'Your appointment with Dr. Rahul Sharma on 20 Aug 2026 has been confirmed.',
    timeAgo: '2 min ago',
    isRead: false,
    iconType: 'success',
  },
  {
    _id: 'n2',
    type: 'appointment_booked',
    title: 'Appointment Request Sent',
    message: 'Your appointment request has been sent to ABC Healthcare Clinic.',
    timeAgo: '1 hour ago',
    isRead: true,
    iconType: 'info',
  },
  {
    _id: 'n3',
    type: 'appointment_rejected',
    title: 'Appointment Rejected',
    message: 'Your appointment request on 15 Aug 2025 has been rejected by the clinic.',
    timeAgo: '2 days ago',
    isRead: true,
    iconType: 'error',
  },
  {
    _id: 'n4',
    type: 'appointment_completed',
    title: 'Appointment Completed',
    message: 'Your appointment with Dr. Priya Verma on 10 Aug 2025 is completed.',
    timeAgo: '3 days ago',
    isRead: true,
    iconType: 'complete',
  },
];
